spring:
  profiles:
    default: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console


cloudinary:
  cloudName: dcqsz042g
  apiKey: 786245647955224
  apiSecret: sbj0b1NVqW5ztYOAkn43jRjI1pQ
